name: 'CI'

on: [push]

jobs:

  security-scan-nag:
    runs-on: ubuntu-latest
    if: always()
    steps:
    - uses: actions/checkout@v2
    - uses: grolston/cfn-security@master
      with:
        cloudformation_directory: "./cloudformation/"
        scanner: "cfn-nag"

  security-scan-checkov:
    runs-on: ubuntu-latest
    if: always()
    steps:
    - uses: actions/checkout@v2
    - uses: grolston/cfn-security@master
      with:
        cloudformation_directory: "./cloudformation/"
        scanner: "checkov"
